### ISSUE TITLE
The website is 404

### ISSUE THREAD

**Issue by teinett** [mdx-js/showcase#24]
The website https://showcase.mdxjs.com/ is 404 error.

```
404: NOT_FOUND 
Code: NOT_FOUND 
ID: cdg1::59gvw-1625839227656-5ab6b2a8d79c
```
<img width="1117" alt="2021-07-09 в 17 00 35" src="https://user-images.githubusercontent.com/1038168/125089664-395e3d80-e0d7-11eb-8c3f-0b7687854467.png">

**Comment by ungoldman** [comment]
👋 came here to post this ^

**Comment by wooorm** [comment]
yeah, it’s been broken for a while. I need to at some point figure out how to crawl tons of sites (preferably in light and dark mode) 🤷‍♂️

**Comment by wooorm** [comment]
Closing this as I am archiving this repo. I have no plans currently to make a replacement showcase. The main website is in the [`mdx-js/mdx` monorepo](https://github.com/mdx-js/mdx/). Thanks!
